insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (1, 'DictumstMorbi.mp3', 'Mr', 'Electronics', 868.49, 4385);
insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (2, 'Vel.txt', 'Ms', 'Home & Kitchen', 596.61, 488);
insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (3, 'PedeLobortisLigula.mp3', 'Rev', 'Home & Kitchen', 533.35, 4449);
insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (4, 'Rutrum.ppt', 'Honorable', 'Home & Kitchen', 676.09, 5530);
insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (5, 'PlateaDictumstEtiam.txt', 'Honorable', 'Electronics', 480.3, 7127);
insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (6, 'PharetraMagnaAc.mp3', 'Dr', 'Electronics', 530.46, 3961);
insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (7, 'LacusPurusAliquet.xls', 'Mrs', 'Beauty', 698.44, 4886);
insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (8, 'IdConsequat.avi', 'Mrs', 'Electronics', 801.91, 6029);
insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (9, 'Hac.mp3', 'Honorable', 'Electronics', 548.69, 3069);
insert into product_table (product_id, product_image, product_name, product_category, price, stock) values (10, 'Accumsan.jpeg', 'Ms', 'Home & Kitchen', 60.78, 58);
